name: netlify-deploy

on:
  workflow_run:
    workflows: ['netlify-build']
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy to Netlify
        run: |
          ls -l netlify_build/
          DEBUG=* netlify deploy
